Mentoria horarios fix
2020-1-RDM/Frontend pull request #24
Opened 2020-06-16 22:07 UTC by johnnyloreano

Telas de Mentorias Disponíveis e Mentor possuem as cards com os horários;
Na tela de Mentoria Disponivel, quando clica no horário, abre uma modal que libera pra marcar uma mentoria. Ao marcar uma mentoria, volta pra tela de categoria de mentorias.
Na tela de Mentor, como ele não marcaria a própria mentoria, foi removido o hover dos horários;
Foi criado um atributo NotHoverable pra desabilitar hover nos horários das cards;
Mensagens de sucesso e falha ao marcar mentoria;

2020-06-17 04:53 UTC, alexandrebing requested changes
O card, de modo geral, está bem diferente do que está na dev... A mudança no estilo foi proposital?

2020-06-17 04:53 UTC, alexandrebing commented on src/components/RedeCard/StyledComponents/index.jsx
> +>>>>>>> develop
Conflito não resolvido aqui

2020-06-17 05:09 UTC, alexandrebing commented
Os botões para tornar a Mentoria invisível, editar e excluir também parecem não funcionar

2020-06-29 17:28 UTC, larissafiorini commented
Este PR não precisa mais ser mergeado, essas alterações acabaram sendo incluídas em outra branch.

2020-06-29 17:28 UTC, closed without merging